<?
  $addThis = $this->addThis();
  if (!empty($addThis)) {
    $this->headScript()->appendFile('https://s7.addthis.com/js/250/addthis_widget.js?pub=' . urlencode($addThis));
  }

  // Set up some variables for convenience:
  $id = $this->driver->getUniqueId();
  $controllerClass = 'controller:' . $this->record($this->driver)->getController();
  $cart = $this->cart();
  $cartId = $this->driver->getResourceSource() . '|' . $id;
?>
<div class="centered-pills noprint">
  <ul class="nav nav-pills">
    <? if (count($this->driver->getCitationFormats()) > 0): ?>
      <li><a id="cite-record" class="modal-link <?=$controllerClass?>" href="<?=$this->url('record-cite', array('id'=>$id)) ?>" title="<?=$this->transEsc('Cite this')?>"><i class="icon-asterisk"></i> <?=$this->transEsc('Cite this')?></a></li>
    <? endif; ?>
    <li><a id="sms-record" class="modal-link <?=$controllerClass?>" href="<?=$this->url('record-sms', array('id'=>$id)) ?>" title="<?=$this->transEsc('Text this')?>"><i class="icon-phone-sign"></i> <?=$this->transEsc('Text this')?></a></li>
    <li><a id="mail-record" class="modal-link <?=$controllerClass?>" href="<?=$this->url('record-email', array('id'=>$id)) ?>" title="<?=$this->transEsc('Email this')?>"><i class="icon-envelope"></i> <?=$this->transEsc('Email this')?></a></li>

    <? // trico edit 2014.05.02 ah - add zotero button ?>
    <li><a id="zotero-record" class="<?=$controllerClass?>" href="<?=$this->url('digitalarchivesrecord', array('id'=>$id)) ?>?print=false" title="<?=$this->transEsc('Zotero')?>"><i class="icon-list-alt"></i> <?=$this->transEsc('Zotero')?></a></li>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <li><a id="save-record" class="modal-link <?=$controllerClass?>" href="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>" title="<?=$this->transEsc('Add to favorites')?>"><i class="icon-plus-sign"></i> <?=$this->transEsc('Add to favorites')?></a></li>
    <? endif; ?>

    <? // trico edit 2014.06.02 ah - add print button ?>
    <li><a id="print-record" class="<?=$controllerClass?>" href="<?=$this->url('digitalarchivesrecord', array('id'=>$id)) ?>?print=true" title="<?=$this->transEsc('Print')?>"><i class="icon-print"></i> <?=$this->transEsc('Print')?></a></li>

    <? if (!empty($addThis)): ?>
      <li><a class="addThis addthis_button" href="https://www.addthis.com/bookmark.php?v=250&amp;pub=<?=urlencode($addThis)?>"><i class="icon-bookmark"></i> <?=$this->transEsc('Bookmark')?></a></li>
    <? endif; ?>
    <? if ($cart->isActive()): ?>
      <li id="bookbag-menu">
        <input id="cartId" type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
        <a id="cart-add" class="<? if(!$cart->contains($cartId)): ?>correct <? endif ?>hidden" href="#"><i class="icon-plus-sign"></i> <?=$this->transEsc('Add to Book Bag') ?></a>
        <a id="cart-remove" class="<? if($cart->contains($cartId)): ?>correct <? endif ?>hidden" href="#"><i class="icon-minus-sign"></i> <?=$this->transEsc('Remove from Book Bag') ?></a>
        <noscript>
          <form method="post" name="addForm" action="<?=$this->url('cart-home')?>">
            <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
            <? if ($cart->contains($cartId)): ?>
              <input class="btn" type="submit" name="delete" value="<?=$this->transEsc('Remove from Book Bag')?>"/>
            <? else: ?>
              <input class="btn" type="submit" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"/>
            <? endif; ?>
          </form>
        </noscript>
      </li>
    <? endif; ?>
  </ul>
</div>
