Having trouble finding what you need? Here are some example searches from the Digital Collections tab.<br /><br />
Keyword: <br/>
<ul>
  <li>student Haverford graduation [finds records with all three terms]</li>
  <li>&quot;bryn mawr campus&quot; (in quotation marks) [returns more precise results than manifest destiny]</li>
</ul>
Title: Parrots in Captivity [includes titles for books, descriptive titles for photographs, letters, etc.]<br />
Author/Creator: Greene William (in inverted or natural order)<br />
Subject:  Quakers Women  [searches within Library of Congress Subject Headings or within Thesaurus of Graphic Materials terms]
<br /><br />
