Having trouble finding what you need? Here are some example searches from the Books &amp; more tab.<br /><br />
Keyword:<br/>
<ul>
  <li>archaeology Mexico pottery [finds records with all three terms]</li>
  <li>&quot;manifest destiny&quot; (in quotation marks) [returns more precise results than manifest destiny]</li>
</ul>
Title: Ulysses [includes titles for books, movies, etc.]<br />
Journal Title: Economist [includes journals, magazines, and newspapers]<br />
Author/Creator: Herzog Werner (in inverted or natural order)<br />
Subject:  biology dictionaries [searches within Library of Congress Subject Headings]
<br /><br />
More search tips are available here (<a href="http://trilibpages.blogs.brynmawr.edu/searching-books-more/" target="_blank">http://trilibpages.blogs.brynmawr.edu/searching-books-more/</a>).
