<? $editions = $this->related->getResults(); if (!empty($editions)): ?>
  <h4><?=$this->transEsc('Other Editions')?></h4>
  <ul class="nav nav-list open related">
    <? foreach ($editions as $data): ?>
      <li>
        <? $formats = $data->getFormats(); if (count($formats) > 0): ?><span class="<?=preg_replace('/[^a-z0-9]/', '', strtolower($formats[0]))?>"><? endif; ?></span><a href="<?=$this->recordLink()->getUrl($data)?>"><?=$this->escapeHtml($data->getTitle())?><?=$data->getTitleSection() ? '. ' . $this->escapeHtml($data->getTitleSection()) : '' ?></a>
        <? $author = $data->getPrimaryAuthor(); if (!empty($author)): ?>
          <br/><?=$this->transEsc('By')?>: <?=$this->escapeHtml($author);?><? endif; ?>
        <? $pubDates = $data->getPublicationDates(); if (!empty($pubDates)): ?>
          <br/><?=$this->transEsc('Published')?>: (<?=$this->escapeHtml($pubDates[0])?>)<? endif; ?>
      </li>
    <? endforeach; ?>
  </ul>
<? endif; ?>
