<?
    // Set page title.
    $this->headTitle($this->translate('Contact Us'));

?>
<strong><?=$this->transEsc('Bryn Mawr')?></strong>
<ul class="contact-list">
  <li>email: <a href="mailto:library@brynmawr.edu"><?=$this->transEsc('library@brynmawr.edu')?></a></li>
  <li>phone: <?=$this->transEsc('(610) 526-5279')?></li>
  <li>online: <a target="_blank" href="http://www.brynmawr.edu/library/elecref.html">Ask a Librarian</a></li>
</ul>
<strong><?=$this->transEsc('Haverford')?></strong>
<ul class="contact-list">
  <li>email: <a href="mailto:library@haverford.edu"><?=$this->transEsc('library@haverford.edu')?></a></li>
  <li>phone: <?=$this->transEsc('(610) 896-1175')?></li>
  <li>online: <a target="_blank" href="http://library.haverford.edu/research/#help">Ask a Librarian</a></li>
</ul>
<strong><?=$this->transEsc('Swarthmore')?></strong>
<ul class="contact-list">
  <li>email: <a href="mailto:librarian@swarthmore.edu"><?=$this->transEsc('librarian@swarthmore.edu')?></a></li>
  <li><?=$this->transEsc('(610) 328-8493')?></li>
  <li><a target="_blank" href="http://www.swarthmore.edu/libraries/ask-a-librarian.xml">Ask a Librarian</a></li>
</ul>
